// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
extern lv_indev_t *indev_encoder ;

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Spinbox4 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Bar3 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Labelclear = NULL;
lv_obj_t * ui_Labelwifi = NULL;
lv_obj_t * ui_Labelsound = NULL;
// lv_group_t * btn_group;  //按键组

// 模拟电源变量


uint16_t set_voltage = 900; //设定电压10mv为单位
uint16_t set_current = 100;
uint16_t ovp = 4000; //过压
uint16_t ocp = 1000; //过流

void out_value_refresh(void)
{   
    lv_label_set_text_fmt(ui_Label4, "%02d.%02d", ADC.output_vol[0],ADC.output_vol[1]);
    lv_label_set_text_fmt(ui_Label11,"%02d.%02d", ADC.input_vol[0],ADC.input_vol[1]);
    lv_label_set_text_fmt(ui_Label15,"%u°C", ADC.temp);
    lv_bar_set_value(ui_Bar1,ADC.input_vol[0], LV_ANIM_OFF);
    lv_bar_set_value(ui_Bar3,ADC.temp,LV_ANIM_OFF);

}



void ui_event_set_value(lv_event_t * e)
{

    lv_event_code_t event_code = lv_event_get_code(e);
 
     if(event_code == LV_EVENT_CLICKED) {
       
        if( e->user_data == 1) {
            // 按钮4被点击，设置电压值
            set_voltage = lv_spinbox_get_value(ui_Spinbox4);
            lv_label_set_text(ui_Label24,"V");
            lv_obj_set_style_bg_color(ui_Label24,lv_color_hex(0xEB4883), LV_PART_MAIN | LV_STATE_DEFAULT);

           
           
        }
        
        else if( e->user_data == 2) {
            // 按钮5被点击，设置电流值
            set_current = lv_spinbox_get_value(ui_Spinbox4);
            if(set_current > ocp) {
                set_current = ocp; // 限制电流值不超过过流保护值
            }
            lv_obj_set_style_bg_color(ui_Label24,lv_color_hex(0x51E4EB), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(ui_Label24,"I");

            
        }
        else if( e->user_data == 3) {
            // 按钮5被点击，设置过流保护
            ocp = lv_spinbox_get_value(ui_Spinbox4);
            lv_obj_set_style_bg_color(ui_Label24,lv_color_hex(0x4A65C2), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(ui_Label24,"I");
           
        }
        else if( e->user_data == 4) {
            // 按钮5被点击，设置过压保护
            ovp = lv_spinbox_get_value(ui_Spinbox4);
            lv_obj_set_style_bg_color(ui_Label24,lv_color_hex(0xAE4ACF), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(ui_Label24,"V");
            
        }
        else if(e->user_data == 5) {
            // 按钮2被点击，恢复默认设置
            set_voltage = 900;
            set_current = 0;
            ovp = 4000;
            ocp = 1000;
            lv_spinbox_set_value(ui_Spinbox4, 0);
            
            lv_obj_set_style_bg_color(ui_Label24,lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        
    }


}


// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        lv_indev_set_group(indev_encoder, g2);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Screen1, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
 

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 42);
    lv_obj_set_height(ui_Button1, 23);
    lv_obj_set_x(ui_Button1, -125);
    lv_obj_set_y(ui_Button1, 97);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // btn_group = lv_group_create(); //创建按键组
    // lv_indev_set_group(indev_button, btn_group); //

    // lv_group_add_obj(btn_group, ui_Button1); //添加到按键组


    ui_Label18 = lv_label_create(ui_Button1);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, LV_SYMBOL_POWER);

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 42);
    lv_obj_set_height(ui_Button2, 23);
    lv_obj_set_x(ui_Button2, -50);
    lv_obj_set_y(ui_Button2, 97);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelclear = lv_label_create(ui_Button2);
    lv_obj_set_align(ui_Labelclear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelclear, LV_SYMBOL_LOOP);


    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 42);
    lv_obj_set_height(ui_Button3, 23);
    lv_obj_set_x(ui_Button3, 25);
    lv_obj_set_y(ui_Button3, 97);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Button3);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, LV_SYMBOL_LIST);



    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 100);
    lv_obj_set_height(ui_Panel6, 79);
    lv_obj_set_x(ui_Panel6, 105);
    lv_obj_set_y(ui_Panel6, -6);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox4 = lv_spinbox_create(ui_Panel6);
    lv_obj_set_width(ui_Spinbox4, 51);
    lv_obj_set_height(ui_Spinbox4, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Spinbox4, 20);
    lv_obj_set_y(ui_Spinbox4, -16);
    lv_obj_set_align(ui_Spinbox4, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox4, 4, 2);
    lv_spinbox_set_value(ui_Spinbox4, set_voltage);
    lv_spinbox_set_range(ui_Spinbox4, 0, 4000);
    lv_spinbox_set_cursor_pos(ui_Spinbox4, 1 - 1);
    lv_obj_set_style_bg_color(ui_Spinbox4, lv_color_hex(0xFCFCF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinbox4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Spinbox4, lv_color_hex(0xEB4883), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spinbox4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox4, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);
 

    
    ui_Label24 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label24, 51);
    lv_obj_set_height(ui_Label24, 30);
    lv_obj_set_x(ui_Label24, 20);
    lv_obj_set_y(ui_Label24, 18);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "V");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label24, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label24, lv_color_hex(0xEB4883), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // spinbox 控件中选择设定值，按键后更改设定电压值
    ui_Button4 = lv_btn_create(ui_Panel6);
    lv_obj_set_width(ui_Button4, 35);
    lv_obj_set_height(ui_Button4, 14);
    lv_obj_set_x(ui_Button4, -25);
    lv_obj_set_y(ui_Button4, -26);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xEB4883), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label9, 35);
    lv_obj_set_height(ui_Label9, 14);
    lv_obj_set_x(ui_Label9, 1);
    lv_obj_set_y(ui_Label9, 1);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "USET");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Panel6);
    lv_obj_set_width(ui_Button5, 35);
    lv_obj_set_height(ui_Button5, 14);
    lv_obj_set_x(ui_Button5, -25);
    lv_obj_set_y(ui_Button5, -8);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x51E4EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button5, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label13, 35);
    lv_obj_set_height(ui_Label13, 14);
    lv_obj_set_x(ui_Label13, 1);
    lv_obj_set_y(ui_Label13, 1);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "ISET");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Panel6);
    lv_obj_set_width(ui_Button6, 35);
    lv_obj_set_height(ui_Button6, 14);
    lv_obj_set_x(ui_Button6, -25);
    lv_obj_set_y(ui_Button6, 9);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x4A65C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button6, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label10, 35);
    lv_obj_set_height(ui_Label10, 14);
    lv_obj_set_x(ui_Label10, 1);
    lv_obj_set_y(ui_Label10, 1);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "OCP");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Panel6);
    lv_obj_set_width(ui_Button7, 35);
    lv_obj_set_height(ui_Button7, 14);
    lv_obj_set_x(ui_Button7, -25);
    lv_obj_set_y(ui_Button7, 27);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xAE4ACF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button7, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label23, 35);
    lv_obj_set_height(ui_Label23, 14);
    lv_obj_set_x(ui_Label23, 1);
    lv_obj_set_y(ui_Label23, 1);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "OVP");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 100);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_x(ui_Panel7, 105);
    lv_obj_set_y(ui_Panel7, -71);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -5);
    lv_obj_set_y(ui_Label11, 7);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "00.00");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x3B09F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label12 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -31);
    lv_obj_set_y(ui_Label12, -13);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "UIN");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label12, lv_color_hex(0x11F36E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Panel7);
    lv_bar_set_range(ui_Bar1, 0, 40);
    lv_bar_set_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 61);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 15);
    lv_obj_set_y(ui_Bar1, -14);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x3B09F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xE50F4E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 39);
    lv_obj_set_y(ui_Label25, 11);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "V");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x3B09F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 100);
    lv_obj_set_height(ui_Panel8, 59);
    lv_obj_set_x(ui_Panel8, 105);
    lv_obj_set_y(ui_Panel8, 64);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -6);
    lv_obj_set_y(ui_Label3, 11);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "00:00");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF23396), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label7, 35);
    lv_obj_set_height(ui_Label7, 14);
    lv_obj_set_x(ui_Label7, -25);
    lv_obj_set_y(ui_Label7, -14);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "CV");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_consola14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0xFAF306), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_Switch2, 30);
    lv_obj_set_height(ui_Switch2, 14);
    lv_obj_set_x(ui_Switch2, 20);
    lv_obj_set_y(ui_Switch2, -14);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x1EC754), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 55);
    lv_obj_set_height(ui_Bar3, 8);
    lv_obj_set_x(ui_Bar3, 86);
    lv_obj_set_y(ui_Bar3, 107);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xBFB63F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 320);
    lv_obj_set_height(ui_Container1, 18);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -112);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    //// 时间控件

    // ui_Label14 = lv_label_create(ui_Container1);
    // lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_Label14, 2);
    // lv_obj_set_y(ui_Label14, 0);
    // lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label14, "19:00");
    // lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Labelsound =  lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Labelsound, LV_SIZE_CONTENT);   /// 
    lv_obj_set_height(ui_Labelsound, LV_SIZE_CONTENT);    /// 1
    
    lv_obj_align(ui_Labelsound, LV_ALIGN_RIGHT_MID,-10, 0);
    lv_label_set_text(ui_Labelsound,LV_SYMBOL_VOLUME_MAX);
    lv_obj_set_style_text_color(ui_Labelsound, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelsound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwifi = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Labelwifi, LV_SIZE_CONTENT);   /// wifi 图标
    lv_obj_set_height(ui_Labelwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_align(ui_Labelwifi, LV_ALIGN_RIGHT_MID, -40, 0);
    lv_label_set_text(ui_Labelwifi,LV_SYMBOL_WIFI);
    
    lv_obj_set_style_text_color(ui_Labelwifi, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    

    ui_Label16= lv_label_create(ui_Container1);  //蓝牙图标
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Label16, LV_ALIGN_RIGHT_MID);
    // lv_obj_align_to(ui_Label16,ui_Container1,LV_ALIGN_RIGHT_MID,2,0);
    lv_obj_align(ui_Label16, LV_ALIGN_RIGHT_MID, -70, 0);
    lv_label_set_text(ui_Label16, "");
    // lv_label_set_text_fmt(ui_Label16, LV_SYMBOL_VOLUME_MAX    LV_SYMBOL_BLUETOOTH);
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 193);
    lv_obj_set_height(ui_Panel10, 170);
    lv_obj_set_x(ui_Panel10, -50);
    lv_obj_set_y(ui_Panel10, -9);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Label4, 4);
    lv_obj_set_y(ui_Label4, -56);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "00.00");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xEC05FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Label1, 4);
    lv_obj_set_y(ui_Label1, 52);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "00.00");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x09F425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Label2, 4);
    lv_obj_set_y(ui_Label2, -2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "00.00");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xE0FD05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 78);
    lv_obj_set_y(ui_Label5, -56);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "V");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xEC05FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 78);
    lv_obj_set_y(ui_Label6, -2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "A");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xE0FD05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 78);
    lv_obj_set_y(ui_Label8, 52);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "W");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x09F425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label19, 25);
    lv_obj_set_height(ui_Label19, 35);
    lv_obj_set_x(ui_Label19, -76);
    lv_obj_set_y(ui_Label19, -57);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "U");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label19, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label19, lv_color_hex(0xEC05FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label20, 25);
    lv_obj_set_height(ui_Label20, 35);
    lv_obj_set_x(ui_Label20, -76);
    lv_obj_set_y(ui_Label20, 51);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "P");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label20, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label20, lv_color_hex(0x09F425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label21, 25);
    lv_obj_set_height(ui_Label21, 35);
    lv_obj_set_x(ui_Label21, -77);
    lv_obj_set_y(ui_Label21, -3);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "I");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label21, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_consola36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label21, lv_color_hex(0xE0FD05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 137);
    lv_obj_set_y(ui_Label15, 107);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "26°C");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label15, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label15, lv_color_hex(0xBFB63F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL); //切换页面
    lv_obj_add_event_cb(ui_Button4, ui_event_set_value, LV_EVENT_ALL, 1); // 设置电压
    lv_obj_add_event_cb(ui_Button5, ui_event_set_value, LV_EVENT_ALL, 2);// 设置电流
    lv_obj_add_event_cb(ui_Button6, ui_event_set_value, LV_EVENT_ALL, 3);//设置OCP保护
    lv_obj_add_event_cb(ui_Button7, ui_event_set_value, LV_EVENT_ALL, 4);//设置OVP保护

    lv_obj_add_event_cb(ui_Button2, ui_event_set_value, LV_EVENT_ALL, 5);//清空设定值

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Button3 = NULL;
    ui_Panel6 = NULL;
    ui_Spinbox4 = NULL;
    ui_Label24 = NULL;
    ui_Button4 = NULL;
    ui_Label9 = NULL;
    ui_Button5 = NULL;
    ui_Label13 = NULL;
    ui_Button6 = NULL;
    ui_Label10 = NULL;
    ui_Button7 = NULL;
    ui_Label23 = NULL;
    ui_Panel7 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Bar1 = NULL;
    ui_Label25 = NULL;
    ui_Panel8 = NULL;
    ui_Label3 = NULL;
    ui_Label7 = NULL;
    ui_Switch2 = NULL;
    ui_Bar3 = NULL;
    ui_Container1 = NULL;
    ui_Label14 = NULL;
    ui_Panel10 = NULL;
    ui_Label4 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label8 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_Label15 = NULL;

}
