// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Chart1 = NULL;
// event funtions
extern lv_indev_t *indev_encoder ;
lv_group_t * g4;
// build funtions
// 全局变量
static lv_obj_t *chart;
static lv_chart_series_t *ser_voltage;
static lv_chart_series_t *ser_current;
static uint32_t point_counter = 0;
bool paused = true;
// 电压电流数据结构
typedef struct {
    float voltage;
    float current;
    uint32_t timestamp;
} power_data_t;

#define MAX_DATA_POINTS 200
static power_data_t data_log[MAX_DATA_POINTS];
static uint8_t data_index = 0;


void ui_event_Buttonback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
        lv_indev_set_group(indev_encoder, g2);
    }
}

// 缩放回调函数
static void zoom_in_cb(lv_event_t *e) {
    lv_obj_t *chart = (lv_obj_t *)lv_event_get_user_data(e);
    lv_coord_t zoom_x = lv_chart_get_zoom_x(chart);
    zoom_x = zoom_x - LV_IMG_ZOOM_NONE;
    if(zoom_x < LV_IMG_ZOOM_NONE) { // 最大缩放限制
        zoom_x = LV_IMG_ZOOM_NONE;
    }
    lv_chart_set_zoom_x(chart, zoom_x);

}

static void zoom_out_cb(lv_event_t *e) {
    lv_obj_t *chart = (lv_obj_t *)lv_event_get_user_data(e);
    lv_coord_t zoom_x = lv_chart_get_zoom_x(chart);

    zoom_x = zoom_x + LV_IMG_ZOOM_NONE;
    if(zoom_x > 1280) { // 最小缩放限制
         zoom_x = LV_IMG_ZOOM_NONE*5;
        
    }
    lv_chart_set_zoom_x(chart, zoom_x);

}
static void pause_resume_cb(lv_event_t *e) {
    paused = !paused;
    
    lv_obj_t *btn = lv_event_get_target(e);
    lv_obj_t *label = lv_obj_get_child(btn, NULL);
    
    if(paused) {
        lv_label_set_text(label, "resume");
        // 停止更新图表
        // lv_timer_pause(timer);
    } else {
        lv_label_set_text(label, "pause");
        // 恢复更新图表
        // lv_timer_resume(timer);
    }
}



// 创建电压电流图表
void create_power_chart(lv_obj_t *parent) {
    // 创建图表对象
    chart = lv_chart_create(parent);
    lv_obj_set_size(chart, 250, 150);
    lv_obj_align(chart, LV_ALIGN_CENTER, 0, 0);
    
    // 设置图表类型为折线图
    lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
    
    // 设置数据点数量
    lv_chart_set_point_count(chart, MAX_DATA_POINTS);
    
    // 设置范围
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 40);   // 电压范围 0-100V
    lv_chart_set_range(chart, LV_CHART_AXIS_SECONDARY_Y, 0, 15);  // 电流范围 0-20A
    
    // 添加网格
    lv_chart_set_div_line_count(chart, 5, 7); // 水平5条，垂直7条
    
    // 创建电压数据系列 (主Y轴)
    ser_voltage = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);
    
    // 创建电流数据系列 (次Y轴)
    ser_current = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_BLUE), LV_CHART_AXIS_SECONDARY_Y);
    
    // 设置数据点样式
    lv_obj_set_style_size(chart, 0, LV_PART_INDICATOR); // 隐藏数据点
    
    // 添加轴标签
    lv_obj_t *label;
    
    // 电压轴标签
    label = lv_label_create(chart);
    lv_label_set_text(label, "U(V)");
    lv_obj_set_style_text_color(label, lv_palette_main(LV_PALETTE_RED), 0);
    lv_obj_align(label, LV_ALIGN_TOP_LEFT, 5, 5);
    lv_chart_set_axis_tick(chart,LV_CHART_AXIS_PRIMARY_Y,5,2,4,1,true,30);
    // 电流轴标签
    label = lv_label_create(chart);
    lv_label_set_text(label, "I(A)");
    lv_obj_set_style_text_color(label, lv_palette_main(LV_PALETTE_BLUE), 0);
    lv_obj_align(label, LV_ALIGN_TOP_RIGHT, -5, 5);
    lv_chart_set_axis_tick(chart,LV_CHART_AXIS_SECONDARY_Y,5,2,4,1,true,30);
    // 添加X轴时间标签
    label = lv_label_create(chart);
    lv_label_set_text(label, "time(s)");
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, -5);
    
    // 添加缩放控制按钮
    lv_obj_t *btn_zoom_in = lv_btn_create(parent);
    lv_obj_set_size(btn_zoom_in, 40, 30);
    lv_obj_align_to(btn_zoom_in, chart, LV_ALIGN_OUT_BOTTOM_RIGHT, -50, 10);
    lv_obj_t *label_btn = lv_label_create(btn_zoom_in);
    lv_label_set_text(label_btn, "+");
    lv_obj_set_style_bg_color(btn_zoom_in, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(btn_zoom_in, zoom_in_cb, LV_EVENT_CLICKED, chart);
    lv_group_add_obj(g4,btn_zoom_in);

    lv_obj_t *btn_zoom_out = lv_btn_create(parent);
    lv_obj_set_size(btn_zoom_out, 40, 30);
    lv_obj_align_to(btn_zoom_out, chart, LV_ALIGN_OUT_BOTTOM_RIGHT, 0, 10);
    label_btn = lv_label_create(btn_zoom_out);
    lv_label_set_text(label_btn, "-");
    lv_obj_set_align(label_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(btn_zoom_out, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g4,btn_zoom_out);
    lv_obj_add_event_cb(btn_zoom_out, zoom_out_cb, LV_EVENT_CLICKED, chart);
    
    // 添加暂停/继续按钮
    static bool paused = false;
    lv_obj_t *btn_pause = lv_btn_create(parent);
    lv_obj_set_size(btn_pause, 80, 30);
    lv_obj_align_to(btn_pause, chart, LV_ALIGN_OUT_BOTTOM_LEFT, 10, 10);
    label_btn = lv_label_create(btn_pause);
    lv_obj_set_align(label_btn, LV_ALIGN_CENTER);
    lv_label_set_text(label_btn, "pause");
    lv_obj_set_style_bg_color(btn_pause, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g4,btn_pause);
    lv_obj_add_event_cb(btn_pause,pause_resume_cb , LV_EVENT_CLICKED, NULL);
    
    lv_obj_t *btn_back = lv_btn_create(parent);
   
    lv_obj_set_width(btn_back, 28);
    lv_obj_set_height(btn_back, 22);
    lv_obj_align(btn_back, LV_ALIGN_TOP_LEFT,10,10);
    lv_obj_add_flag(btn_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(btn_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(btn_back, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(btn_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g4,btn_back);
    
    lv_obj_t *btn_label = lv_label_create(btn_back);
    lv_obj_set_align(btn_label,LV_ALIGN_CENTER);
    lv_label_set_text_fmt(btn_label, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_font(btn_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    lv_obj_add_event_cb(btn_back, ui_event_Buttonback, LV_EVENT_ALL, NULL);





    // 初始化数据数组
    for(int i = 0; i < MAX_DATA_POINTS; i++) {
        data_log[i].voltage = 0;
        data_log[i].current = 0;
        data_log[i].timestamp = i;
        lv_chart_set_next_value(chart, ser_voltage, 0);
        lv_chart_set_next_value(chart, ser_current, 0);
    }
}


// 更新图表数据 (在定时器或数据采集回调中调用)
void update_power_chart(uint16_t voltage, uint16_t current) {
    
    if(paused) return;
    
    // 保存数据到历史记录
    data_log[data_index].voltage = voltage;
    data_log[data_index].current = current;
    data_log[data_index].timestamp = point_counter;
    
    // 更新图表数据
    lv_chart_set_next_value(chart, ser_voltage, (int32_t)(voltage )); // 乘以10保留1位小数
    lv_chart_set_next_value(chart, ser_current, (int32_t)(current )); // 乘以100保留2位小数
    
    // 更新索引
    data_index = (data_index + 1) % MAX_DATA_POINTS;
    point_counter++;
    
    // 每10个点刷新一次图表
    if(point_counter % 10 == 0) {
        lv_chart_refresh(chart);
    }
    
   
}



// 添加图例
void add_chart_legend() {
    // 创建图例容器
    lv_obj_t *legend = lv_obj_create(lv_scr_act());
    lv_obj_set_size(legend, 120, 40);
    lv_obj_align_to(legend, chart, LV_ALIGN_OUT_TOP_RIGHT, 0, -10);
    lv_obj_set_style_border_width(legend, 0, 0);
    lv_obj_set_style_bg_opa(legend, LV_OPA_0, 0);
    lv_obj_set_flex_flow(legend, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(legend, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    
    // 电压图例
    lv_obj_t *voltage_legend = lv_obj_create(legend);
    lv_obj_set_size(voltage_legend, 50, 20);
    lv_obj_set_style_border_width(voltage_legend, 0, 0);
    
    // 电压颜色标识
    lv_obj_t *color_ind = lv_obj_create(voltage_legend);
    lv_obj_set_size(color_ind, 10, 10);
    lv_obj_set_style_bg_color(color_ind, lv_palette_main(LV_PALETTE_RED), 0);
    lv_obj_align(color_ind, LV_ALIGN_LEFT_MID, 0, 0);
    
    // 电压文本
    lv_obj_t *label = lv_label_create(voltage_legend);
    lv_label_set_text(label, "U");
    lv_obj_align_to(label, color_ind, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    
    // 电流图例
    lv_obj_t *current_legend = lv_obj_create(legend);
    lv_obj_set_size(current_legend, 50, 20);
    lv_obj_set_style_border_width(current_legend, 0, 0);
    
    // 电流颜色标识
    color_ind = lv_obj_create(current_legend);
    lv_obj_set_size(color_ind, 10, 10);
    lv_obj_set_style_bg_color(color_ind, lv_palette_main(LV_PALETTE_BLUE), 0);
    lv_obj_align(color_ind, LV_ALIGN_LEFT_MID, 0, 0);
    
    // 电流文本
    label = lv_label_create(current_legend);
    lv_label_set_text(label, "I");
    lv_obj_align_to(label, color_ind, LV_ALIGN_OUT_RIGHT_MID, 5, 0);

    
}


void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    g4= lv_group_create();
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    create_power_chart(ui_Screen4);
    add_chart_legend();

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Chart1 = NULL;

}
