// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
extern lv_indev_t *indev_encoder ;
lv_group_t * g3;
// event funtions
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
        lv_indev_set_group(indev_encoder, g2);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{   
    g3 = lv_group_create(); //第二个页面的组
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 256);
    lv_obj_set_height(ui_Panel1, 218);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -2);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_Panel1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 111);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 43);
    lv_obj_set_y(ui_Slider1, 45);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g3,ui_Slider1);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 74);
    lv_obj_set_y(ui_Switch1, -55);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_group_add_obj(g3,ui_Switch1);

    ui_Slider2 = lv_slider_create(ui_Panel1);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 108);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 43);
    lv_obj_set_y(ui_Slider2, 83);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_group_add_obj(g3,ui_Slider2);

    ui_Switch3 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 75);
    lv_obj_set_y(ui_Switch3, -2);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_group_add_obj(g3,ui_Switch3);

    ui_Button11 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_Button11, 28);
    lv_obj_set_height(ui_Button11, 22);
    lv_obj_set_x(ui_Button11, -109);
    lv_obj_set_y(ui_Button11, -95);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g3,ui_Button11);

    ui_Label29 = lv_label_create(ui_Button11);
    lv_obj_set_align(ui_Label29,LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label29, LV_SYMBOL_LEFT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -71);
    lv_obj_set_y(ui_Label22, -56);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Bluetooth");

    ui_Label26 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -92);
    lv_obj_set_y(ui_Label26, -4);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Wifi");

    ui_Label27 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -71);
    lv_obj_set_y(ui_Label27, 43);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Backlight");

    ui_Label28 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -92);
    lv_obj_set_y(ui_Label28, 81);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Fan");

    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel1 = NULL;
    ui_Slider1 = NULL;
    ui_Switch1 = NULL;
    ui_Slider2 = NULL;
    ui_Switch3 = NULL;
    ui_Button11 = NULL;
    ui_Label22 = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;

}
