// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
extern lv_indev_t *indev_encoder ;
lv_group_t * g2;
lv_obj_t * ui_Screen2 = NULL;
void ui_event_Buttonhome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        lv_indev_set_group(indev_encoder, lv_group_get_default());
    }
}


static void scroll_event_cb(lv_event_t * e)
{
    lv_obj_t * cont = lv_event_get_target(e);

    lv_area_t cont_a;
    lv_obj_get_coords(cont, &cont_a);
    lv_coord_t cont_y_center = cont_a.y1 + lv_area_get_height(&cont_a) / 2;

    lv_coord_t r = lv_obj_get_height(cont) * 7 / 10;
    uint32_t i;
    uint32_t child_cnt = lv_obj_get_child_cnt(cont);
    for(i = 0; i < child_cnt; i++) {
        lv_obj_t * child = lv_obj_get_child(cont, i);
        lv_area_t child_a;
        lv_obj_get_coords(child, &child_a);

        lv_coord_t child_y_center = child_a.y1 + lv_area_get_height(&child_a) / 2;

        lv_coord_t diff_y = child_y_center - cont_y_center;
        diff_y = LV_ABS(diff_y);

        /*Get the x of diff_y on a circle.*/
        lv_coord_t x;
        /*If diff_y is out of the circle use the last point of the circle (the radius)*/
        if(diff_y >= r) {
            x = r;
        }
        else {
            /*Use Pythagoras theorem to get x from radius and y*/
            uint32_t x_sqr = r * r - diff_y * diff_y;
            lv_sqrt_res_t res;
            lv_sqrt(x_sqr, &res, 0x8000);   /*Use lvgl's built in sqrt root function*/
            x = r - res.i;
        }

        /*Translate the item by the calculated X coordinate*/
        lv_obj_set_style_translate_x(child, x, 0);

        /*Use some opacity with larger translations*/
        lv_opa_t opa = lv_map(x, 0, r, LV_OPA_TRANSP, LV_OPA_COVER);
        lv_obj_set_style_opa(child, LV_OPA_COVER - opa, 0);
    }
}

/**
 * Translate the object as they scroll
 */
void lv_example_scroll_6(void)
{
    lv_obj_t * cont = lv_obj_create(ui_Screen2);
    lv_obj_set_size(cont, 300, 200);
    lv_obj_center(cont);
    lv_obj_set_flex_flow(cont, LV_FLEX_FLOW_COLUMN);
    lv_obj_add_event_cb(cont, scroll_event_cb, LV_EVENT_SCROLL, NULL);
    // lv_obj_set_style_radius(cont, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_clip_corner(cont, true, 0);
    lv_obj_set_scroll_dir(cont, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(cont, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scrollbar_mode(cont, LV_SCROLLBAR_MODE_OFF);
    // lv_group_add_obj(g2,cont);
  

    
    lv_obj_t * btn1 = lv_btn_create(cont);
    lv_obj_set_size(btn1, 280,70);

    lv_obj_t * label = lv_label_create(btn1);
    lv_obj_set_align(label,LV_ALIGN_LEFT_MID);

    lv_label_set_text_fmt(label, LV_SYMBOL_SETTINGS"  Settings ");
    lv_obj_set_style_bg_color(btn1, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_group_add_obj(g2,btn1);

    lv_obj_t * btn2 = lv_btn_create(cont);
    lv_obj_set_size(btn2, 280,70);

    lv_obj_t * label2 = lv_label_create(btn2);
    lv_obj_set_align(label2,LV_ALIGN_LEFT_MID);
    lv_label_set_text_fmt(label2, LV_SYMBOL_PLAY"  Charts ");
    lv_obj_set_style_bg_color(btn2, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g2,btn2);

    lv_obj_t * btn4 = lv_btn_create(cont);
    lv_obj_set_size(btn4, 280,70);

    lv_obj_t * label4 = lv_label_create(btn4);
    lv_obj_set_align(label4,LV_ALIGN_LEFT_MID);
    lv_label_set_text_fmt(label4, LV_SYMBOL_FILE"  Info ");
    lv_obj_set_style_bg_color(btn4, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g2,btn4);



    lv_obj_t * btn3 = lv_btn_create(cont);
    lv_obj_set_size(btn3, 280,70);

    lv_obj_t * label3 = lv_label_create(btn3);
    lv_obj_set_align(label3,LV_ALIGN_LEFT_MID);
    lv_label_set_text_fmt(label3, LV_SYMBOL_HOME"  Home ");
    lv_obj_set_style_bg_color(btn3, lv_color_hex(0x646060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_group_add_obj(g2,btn3);
    

    /*Update the buttons position manually for first*/
    lv_event_send(cont, LV_EVENT_SCROLL, NULL);

    /*Be sure the fist button is in the middle*/
    lv_obj_scroll_to_view(lv_obj_get_child(cont, 0), LV_ANIM_OFF);

    lv_obj_add_event_cb(btn3, ui_event_Buttonhome, LV_EVENT_ALL, NULL);
}


void ui_Screen2_screen_init(void)
{
    g2 = lv_group_create(); //第二个页面的组
    


    ui_Screen2 = lv_obj_create(NULL);

    lv_example_scroll_6();
    

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    // ui_Button8 = NULL;
    // ui_Label17 = NULL;

}
