// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Spinbox4;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16 ;
extern lv_obj_t * ui_Labelwifi ;
extern lv_obj_t * ui_Labelsound ;

extern uint16_t set_voltage ;
extern uint16_t set_current ;
extern uint16_t ovp; //过压
extern uint16_t ocp; //过流
// CUSTOM VARIABLES
void simulate_output_voltage(void);
void out_value_refresh(void);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

