// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Chart1;
extern lv_group_t * g4;
extern bool paused;
// CUSTOM VARIABLES
void update_power_chart(uint16_t voltage, uint16_t current);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

