// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Chart1 = NULL;
// event funtions
extern lv_indev_t *indev_encoder ;
lv_group_t * g4;
// build funtions
// 全局变量
static lv_obj_t *chart;
static lv_chart_series_t *ser_voltage;
static lv_chart_series_t *ser_current;
static uint32_t point_counter = 0;

// 电压电流数据结构
typedef struct {
    float voltage;
    float current;
    uint32_t timestamp;
} power_data_t;

#define MAX_DATA_POINTS 100
static power_data_t data_log[MAX_DATA_POINTS];
static uint8_t data_index = 0;

// 创建电压电流图表
void create_power_chart(lv_obj_t *parent) {
    // 创建图表对象
    chart = lv_chart_create(parent);
    lv_obj_set_size(chart, 300, 200);
    lv_obj_align(chart, LV_ALIGN_CENTER, 0, 0);
    
    // 设置图表类型为折线图
    lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
    
    // 设置数据点数量
    lv_chart_set_point_count(chart, MAX_DATA_POINTS);
    
    // 设置范围
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 100);   // 电压范围 0-100V
    lv_chart_set_range(chart, LV_CHART_AXIS_SECONDARY_Y, 0, 20);  // 电流范围 0-20A
    
    // 添加网格
    lv_chart_set_div_line_count(chart, 5, 7); // 水平5条，垂直7条
    
    // 创建电压数据系列 (主Y轴)
    ser_voltage = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);
    
    // 创建电流数据系列 (次Y轴)
    ser_current = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_BLUE), LV_CHART_AXIS_SECONDARY_Y);
    
    // 设置数据点样式
    lv_obj_set_style_size(chart, 0, LV_PART_INDICATOR); // 隐藏数据点
    
    // 添加轴标签
    lv_obj_t *label;
    
    // 电压轴标签
    label = lv_label_create(chart);
    lv_label_set_text(label, "U(V)");
    lv_obj_set_style_text_color(label, lv_palette_main(LV_PALETTE_RED), 0);
    lv_obj_align(label, LV_ALIGN_TOP_LEFT, 5, 5);
    
    // 电流轴标签
    label = lv_label_create(chart);
    lv_label_set_text(label, "I(A)");
    lv_obj_set_style_text_color(label, lv_palette_main(LV_PALETTE_BLUE), 0);
    lv_obj_align(label, LV_ALIGN_TOP_RIGHT, -5, 5);
    
    // 添加X轴时间标签
    label = lv_label_create(chart);
    lv_label_set_text(label, "time(s)");
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, -5);
    
    // 添加缩放控制按钮
    lv_obj_t *btn_zoom_in = lv_btn_create(parent);
    lv_obj_set_size(btn_zoom_in, 40, 30);
    lv_obj_align_to(btn_zoom_in, chart, LV_ALIGN_OUT_BOTTOM_RIGHT, -50, 10);
    lv_obj_t *label_btn = lv_label_create(btn_zoom_in);
    lv_label_set_text(label_btn, "+");
    // lv_obj_add_event_cb(btn_zoom_in, zoom_in_cb, LV_EVENT_CLICKED, chart);
    
    lv_obj_t *btn_zoom_out = lv_btn_create(parent);
    lv_obj_set_size(btn_zoom_out, 40, 30);
    lv_obj_align_to(btn_zoom_out, chart, LV_ALIGN_OUT_BOTTOM_RIGHT, 0, 10);
    label_btn = lv_label_create(btn_zoom_out);
    lv_label_set_text(label_btn, "-");
    // lv_obj_add_event_cb(btn_zoom_out, zoom_out_cb, LV_EVENT_CLICKED, chart);
    
    // 添加暂停/继续按钮
    static bool paused = false;
    lv_obj_t *btn_pause = lv_btn_create(parent);
    lv_obj_set_size(btn_pause, 80, 30);
    lv_obj_align_to(btn_pause, chart, LV_ALIGN_OUT_BOTTOM_LEFT, 10, 10);
    label_btn = lv_label_create(btn_pause);
    lv_label_set_text(label_btn, "pause");
    // lv_obj_add_event_cb(btn_pause, [](lv_event_t *e) {
    //     paused = !paused;
    //     lv_label_set_text(lv_obj_get_child(e->target, 0), paused ? "start" : "pause");
    // }, LV_EVENT_CLICKED, NULL);
    
    // 初始化数据数组
    for(int i = 0; i < MAX_DATA_POINTS; i++) {
        data_log[i].voltage = 0;
        data_log[i].current = 0;
        data_log[i].timestamp = i;
        lv_chart_set_next_value(chart, ser_voltage, 0);
        lv_chart_set_next_value(chart, ser_current, 0);
    }
}

// 缩放回调函数
static void zoom_in_cb(lv_event_t *e) {
    lv_obj_t *chart = (lv_obj_t *)lv_event_get_user_data(e);
    lv_coord_t zoom_x = lv_chart_get_zoom_x(chart);
    if(zoom_x < 256) { // 最大缩放限制
        lv_chart_set_zoom_x(chart, zoom_x * 2);
    }
}

static void zoom_out_cb(lv_event_t *e) {
    lv_obj_t *chart = (lv_obj_t *)lv_event_get_user_data(e);
    lv_coord_t zoom_x = lv_chart_get_zoom_x(chart);
    if(zoom_x > 1) { // 最小缩放限制
        lv_chart_set_zoom_x(chart, zoom_x / 2);
    }
}
// 自动调整图表范围
void adjust_chart_range(void) {
    float max_voltage = 0;
    float min_voltage = 1000;
    float max_current = 0;
    float min_current = 1000;
    
    // 查找最小/最大值
    for(int i = 0; i < MAX_DATA_POINTS; i++) {
        if(data_log[i].voltage > max_voltage) max_voltage = data_log[i].voltage;
        if(data_log[i].voltage < min_voltage) min_voltage = data_log[i].voltage;
        if(data_log[i].current > max_current) max_current = data_log[i].current;
        if(data_log[i].current < min_current) min_current = data_log[i].current;
    }
    
    // 添加10%的裕量
    float voltage_range = max_voltage - min_voltage;
    float current_range = max_current - min_current;
    
    if(voltage_range < 1) voltage_range = 10; // 防止除零
    if(current_range < 0.1) current_range = 2;
    
    // 设置电压轴范围
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 
                      (int32_t)((min_voltage - voltage_range * 0.1) * 10),
                      (int32_t)((max_voltage + voltage_range * 0.1) * 10));
    
    // 设置电流轴范围
    lv_chart_set_range(chart, LV_CHART_AXIS_SECONDARY_Y, 
                      (int32_t)((min_current - current_range * 0.1) * 100),
                      (int32_t)((max_current + current_range * 0.1) * 100));
}

// 更新图表数据 (在定时器或数据采集回调中调用)
void update_power_chart(float voltage, float current) {
    static bool paused = false;
    if(paused) return;
    
    // 保存数据到历史记录
    data_log[data_index].voltage = voltage;
    data_log[data_index].current = current;
    data_log[data_index].timestamp = point_counter;
    
    // 更新图表数据
    lv_chart_set_next_value(chart, ser_voltage, (int32_t)(voltage * 10)); // 乘以10保留1位小数
    lv_chart_set_next_value(chart, ser_current, (int32_t)(current * 100)); // 乘以100保留2位小数
    
    // 更新索引
    data_index = (data_index + 1) % MAX_DATA_POINTS;
    point_counter++;
    
    // 每10个点刷新一次图表
    if(point_counter % 10 == 0) {
        lv_chart_refresh(chart);
    }
    
    // 自动调整范围 (每100点检查一次)
    static uint32_t last_range_check = 0;
    if(point_counter - last_range_check > 100) {
        last_range_check = point_counter;
        adjust_chart_range();
    }
}


// 添加图例
void add_chart_legend() {
    // 创建图例容器
    lv_obj_t *legend = lv_obj_create(lv_scr_act());
    lv_obj_set_size(legend, 120, 40);
    lv_obj_align_to(legend, chart, LV_ALIGN_OUT_TOP_RIGHT, 0, -10);
    lv_obj_set_style_border_width(legend, 0, 0);
    lv_obj_set_style_bg_opa(legend, LV_OPA_0, 0);
    lv_obj_set_flex_flow(legend, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(legend, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    
    // 电压图例
    lv_obj_t *voltage_legend = lv_obj_create(legend);
    lv_obj_set_size(voltage_legend, 50, 20);
    lv_obj_set_style_border_width(voltage_legend, 0, 0);
    
    // 电压颜色标识
    lv_obj_t *color_ind = lv_obj_create(voltage_legend);
    lv_obj_set_size(color_ind, 10, 10);
    lv_obj_set_style_bg_color(color_ind, lv_palette_main(LV_PALETTE_RED), 0);
    lv_obj_align(color_ind, LV_ALIGN_LEFT_MID, 0, 0);
    
    // 电压文本
    lv_obj_t *label = lv_label_create(voltage_legend);
    lv_label_set_text(label, "U");
    lv_obj_align_to(label, color_ind, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
    
    // 电流图例
    lv_obj_t *current_legend = lv_obj_create(legend);
    lv_obj_set_size(current_legend, 50, 20);
    lv_obj_set_style_border_width(current_legend, 0, 0);
    
    // 电流颜色标识
    color_ind = lv_obj_create(current_legend);
    lv_obj_set_size(color_ind, 10, 10);
    lv_obj_set_style_bg_color(color_ind, lv_palette_main(LV_PALETTE_BLUE), 0);
    lv_obj_align(color_ind, LV_ALIGN_LEFT_MID, 0, 0);
    
    // 电流文本
    label = lv_label_create(current_legend);
    lv_label_set_text(label, "I");
    lv_obj_align_to(label, color_ind, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
}


void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    create_power_chart(ui_Screen4);
    add_chart_legend();

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Chart1 = NULL;

}
